apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: joy
  name: nuxt-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nuxt-app
  template:
    metadata:
      labels:
        app: nuxt-app
    spec:
      containers:
        - name: nuxt-app
          image: registry.infra.kagescan.fr/s9-cloud-nuxt:v0.3
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  namespace: joy
  name: nuxt-service
spec:
  type: LoadBalancer
  selector:
    app: nuxt-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
