apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: joy
  name: api-publication
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-publication
  template:
    metadata:
      labels:
        app: api-publication
    spec:
      containers:
        - name: api-publication
          image: registry.infra.kagescan.fr/s9-cloud-publication:v0.2
          ports:
            - containerPort: 8001
          envFrom:
            - secretRef:
                name: postgres-secret
          env:
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_NAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_HOST

            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PORT
          lifecycle:
            postStart:
              exec:
                command: [ "sh", "-c", "python manage.py makemigrations publication && python manage.py migrate publication" ]


---

apiVersion: v1
kind: Service
metadata:
  name: publication-service
  namespace: joy
spec:
  type: LoadBalancer
  selector:
    app: api-publication
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8001
