@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQxMTk4NzgxLCJpYXQiOjE3NDExOTY5ODEsImp0aSI6IjNjYWU4N2E1NjQ0MjRlMWI4MDIyZjI1ZTc4ZDRjYzY1IiwidXNlcl9pZCI6MX0.IR3XoU1YeEslpuM55jCV4gfw4a1WUukSQ57rrUXYNB4

###
POST http://localhost:8000/api/auth/register
Content-Type: application/json

{
  "email": "yasmine@ex.com",
  "password": "123456"
}
###
POST http://localhost:8000/api/auth/login
Content-Type: application/json

{
   "email": "yasmine@ex.com",
    "password": "123456"
}

### Publication GET ###
GET http://localhost:8001/api/publications
Content-type: application/json
Authorization: Bearer {{token}}

### Publiation POST ###
POST http://localhost:8001/api/publications
Content-type: application/json
Authorization: Bearer {{token}}

{
  "title": "Test",
  "body": "Test"
}
### Publication PUT ###
PUT http://localhost:8001/api/publications/1
Content-type: application/json
Authorization: Bearer {{token}}

{
  "title": "Test1",
  "body": "Test1"
}
### Like POST ###
POST http://localhost:8001/api/publications/1/like
Content-type: application/json
Authorization: Bearer {{token}}
### Like DELETE ###
DELETE http://localhost:8001/api/publications/1/like
Content-type: application/json
Authorization: Bearer {{token}}
### UserProfile GET ###
GET http://localhost:8002/api/profile
Content-type: application/json
Authorization: Bearer {{token}}
### UserProfile PUT ###
PUT http://localhost:8002/api/profile
Content-type: application/json
Authorization: Bearer {{token}}

{
  "username": "newusername"
}