apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: joy
  name: postgres-volume
  labels:
    type: local
    app: postgres
spec:
  storageClassName: ""
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/postgresql