apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: joy
  name: postgres-volume-claim
  labels:
    app: postgres
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
  